AWSTemplateFormatVersion: '2010-09-09'
Resources:
  # ---
  # DynamoDB Table definitions
  # ---
  DDBTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: "Vehicle"
      KeySchema:
        - AttributeName: "id"
          KeyType: "HASH"
      AttributeDefinitions:
        -
          AttributeName: "id"
          AttributeType: "S"
      ProvisionedThroughput:
        ReadCapacityUnits: 10
        WriteCapacityUnits: 5