package com.digital.iqscroll.domain;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

@DynamoDBTable(tableName = "Fact")
public class Fact {
    private String factId;
    private String factImageUrl;
    private String factBodyText;

    public Fact(String factId, String factImageUrl, String factBodyText) {
        this.factId = factId;
        this.factImageUrl = factImageUrl;
        this.factBodyText = factBodyText;
    }

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    public String getFactId() {
        return this.factId;
    }

    @DynamoDBAttribute
    public String getFactImageUrl() {
        return this.factImageUrl;
    }

    @DynamoDBAttribute
    public String getFactBodyText() {
        return this.factBodyText;
    }

    public void setFactId(String factId) {
        this.factId = factId;
    }

    public void setFactImageUrl(String factImageUrl) {
        this.factImageUrl = factImageUrl;
    }

    public void setFactBodyText(String factBodyText) {
        this.factBodyText = factBodyText;
    }
}
